/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PublishRouteImport } from './routes/publish'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClipsIndexRouteImport } from './routes/clips.index'
import { Route as PublishQueueRouteImport } from './routes/publish.queue'
import { Route as PublishHistoryRouteImport } from './routes/publish.history'
import { Route as ClipsClipIdRouteImport } from './routes/clips.$clipId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PublishRoute = PublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClipsIndexRoute = ClipsIndexRouteImport.update({
  id: '/clips/',
  path: '/clips/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublishQueueRoute = PublishQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => PublishRoute,
} as any)
const PublishHistoryRoute = PublishHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => PublishRoute,
} as any)
const ClipsClipIdRoute = ClipsClipIdRouteImport.update({
  id: '/clips/$clipId',
  path: '/clips/$clipId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/history': typeof HistoryRoute
  '/publish': typeof PublishRouteWithChildren
  '/settings': typeof SettingsRoute
  '/clips/$clipId': typeof ClipsClipIdRoute
  '/publish/history': typeof PublishHistoryRoute
  '/publish/queue': typeof PublishQueueRoute
  '/clips/': typeof ClipsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/history': typeof HistoryRoute
  '/publish': typeof PublishRouteWithChildren
  '/settings': typeof SettingsRoute
  '/clips/$clipId': typeof ClipsClipIdRoute
  '/publish/history': typeof PublishHistoryRoute
  '/publish/queue': typeof PublishQueueRoute
  '/clips': typeof ClipsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/history': typeof HistoryRoute
  '/publish': typeof PublishRouteWithChildren
  '/settings': typeof SettingsRoute
  '/clips/$clipId': typeof ClipsClipIdRoute
  '/publish/history': typeof PublishHistoryRoute
  '/publish/queue': typeof PublishQueueRoute
  '/clips/': typeof ClipsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/history'
    | '/publish'
    | '/settings'
    | '/clips/$clipId'
    | '/publish/history'
    | '/publish/queue'
    | '/clips/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/history'
    | '/publish'
    | '/settings'
    | '/clips/$clipId'
    | '/publish/history'
    | '/publish/queue'
    | '/clips'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/history'
    | '/publish'
    | '/settings'
    | '/clips/$clipId'
    | '/publish/history'
    | '/publish/queue'
    | '/clips/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  HistoryRoute: typeof HistoryRoute
  PublishRoute: typeof PublishRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  ClipsClipIdRoute: typeof ClipsClipIdRoute
  ClipsIndexRoute: typeof ClipsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publish': {
      id: '/publish'
      path: '/publish'
      fullPath: '/publish'
      preLoaderRoute: typeof PublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clips/': {
      id: '/clips/'
      path: '/clips'
      fullPath: '/clips/'
      preLoaderRoute: typeof ClipsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publish/queue': {
      id: '/publish/queue'
      path: '/queue'
      fullPath: '/publish/queue'
      preLoaderRoute: typeof PublishQueueRouteImport
      parentRoute: typeof PublishRoute
    }
    '/publish/history': {
      id: '/publish/history'
      path: '/history'
      fullPath: '/publish/history'
      preLoaderRoute: typeof PublishHistoryRouteImport
      parentRoute: typeof PublishRoute
    }
    '/clips/$clipId': {
      id: '/clips/$clipId'
      path: '/clips/$clipId'
      fullPath: '/clips/$clipId'
      preLoaderRoute: typeof ClipsClipIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PublishRouteChildren {
  PublishHistoryRoute: typeof PublishHistoryRoute
  PublishQueueRoute: typeof PublishQueueRoute
}

const PublishRouteChildren: PublishRouteChildren = {
  PublishHistoryRoute: PublishHistoryRoute,
  PublishQueueRoute: PublishQueueRoute,
}

const PublishRouteWithChildren =
  PublishRoute._addFileChildren(PublishRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  HistoryRoute: HistoryRoute,
  PublishRoute: PublishRouteWithChildren,
  SettingsRoute: SettingsRoute,
  ClipsClipIdRoute: ClipsClipIdRoute,
  ClipsIndexRoute: ClipsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
